import Head from "next/head";
import Image from "next/image";
import MidHeading from "../components/mid-Heading/MidHeading";
import NavBar from "../components/navbar/NavBar";
import SearchBar from "../components/search-bar/SearchBar";
import Product from "../components/product/Product";
import styles from "../styles/Home.module.css";

import { useState, useEffect } from "react";

export default function Home() {
  const [products, setProducts] = useState([]);

  useEffect(() => {
    const fetchProducts = async () => {
      const response = await fetch(`api/woodProducts`);
      const data = await response.json();
      setProducts(data);

      // console.log(typeof data);
      // products.map((product) => console.log(product.rows[0].id));
    };

    fetchProducts();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Timberhub Front End Exercise</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />
      <main className={styles.main}>
        <MidHeading />
        <SearchBar />

        <div className={styles.display}>
          <p>Product (Specie, Grade, Drying)</p>
          {products?.map((item) => (
            <Product key={item.rows[0].id} product={item} />
          ))}
        </div>
      </main>
    </div>
  );
}
